import { Theme } from './light';
import { colors, typography, spacing, borderRadius, shadows, animation, zIndex } from './tokens';

export const darkTheme: Theme = {
  name: 'dark',
  isDark: true,
  colors: {
    brand: {
      primary: colors.brand.primaryLight,
      primaryLight: '#A5B4FC',
      primaryDark: colors.brand.primary,
      secondary: colors.brand.secondaryLight,
      secondaryLight: '#F9A8D4',
      accent: colors.brand.accentLight,
      accentLight: '#5EEAD4',
    },
    primary: colors.brand.primaryLight,
    primaryGradient: [...colors.gradients.primary.slice(0, 2).map(c => c === '#6366F1' ? '#818CF8' : c === '#8B5CF6' ? '#A78BFA' : c)] as [string, string],
    primaryGradientFull: [...colors.gradients.primary.map(c => c === '#6366F1' ? '#818CF8' : c === '#8B5CF6' ? '#A78BFA' : c === '#EC4899' ? '#C084FC' : c)] as [string, string, string],
    secondary: colors.brand.secondaryLight,
    success: colors.semantic.successLight,
    successLight: '#6EE7B7',
    warning: colors.semantic.warningLight,
    warningLight: '#FCD34D',
    error: colors.semantic.errorLight,
    errorLight: '#FCA5A5',
    info: colors.semantic.infoLight,
    infoLight: '#93C5FD',
    background: colors.neutral[950],
    backgroundSecondary: colors.neutral[900],
    surface: colors.neutral[900],
    surfaceSecondary: colors.neutral[800],
    surfaceTertiary: colors.neutral[700],
    text: colors.neutral[50],
    textSecondary: colors.neutral[400],
    textTertiary: colors.neutral[500],
    textInverse: colors.neutral[900],
    border: colors.neutral[800],
    borderLight: colors.neutral[900],
    borderDark: colors.neutral[700],
    card: colors.neutral[900],
    cardSecondary: colors.neutral[800],
    cardShadow: 'rgba(0, 0, 0, 0.4)',
    overlay: 'rgba(0, 0, 0, 0.6)',
    overlayLight: 'rgba(0, 0, 0, 0.4)',
    tabBar: {
      active: colors.brand.primaryLight,
      inactive: colors.neutral[500],
      background: colors.neutral[900],
      border: colors.neutral[800],
    },
    statusBadge: {
      new: colors.semantic.errorLight,
      newLight: '#FCA5A5',
      learning: colors.semantic.warningLight,
      learningLight: '#FCD34D',
      mastered: colors.semantic.successLight,
      masteredLight: '#6EE7B7',
    },
    glass: {
      background: 'rgba(39, 39, 42, 0.7)',
      backgroundDark: 'rgba(39, 39, 42, 0.85)',
      border: 'rgba(255, 255, 255, 0.1)',
    },
  },
  typography: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSize,
    fontWeight: typography.fontWeight,
    lineHeight: typography.lineHeight,
    letterSpacing: typography.letterSpacing,
  },
  spacing: spacing,
  borderRadius: borderRadius,
  shadows: {
    ...shadows,
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 2,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 4,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.35,
      shadowRadius: 16,
      elevation: 8,
    },
  },
  animation: animation,
  zIndex: zIndex,
};
