import { colors, typography, spacing, borderRadius, shadows, animation, zIndex } from './tokens';

export const lightTheme = {
  name: 'light',
  isDark: false,
  colors: {
    brand: {
      primary: colors.brand.primary,
      primaryLight: colors.brand.primaryLight,
      primaryDark: colors.brand.primaryDark,
      secondary: colors.brand.secondary,
      secondaryLight: colors.brand.secondaryLight,
      accent: colors.brand.accent,
      accentLight: colors.brand.accentLight,
    },
    primary: colors.brand.primary,
    primaryGradient: [...colors.gradients.primary.slice(0, 2)] as [string, string],
    primaryGradientFull: [...colors.gradients.primary] as [string, string, string],
    secondary: colors.brand.secondary,
    success: colors.semantic.success,
    successLight: colors.semantic.successLight,
    warning: colors.semantic.warning,
    warningLight: colors.semantic.warningLight,
    error: colors.semantic.error,
    errorLight: colors.semantic.errorLight,
    info: colors.semantic.info,
    infoLight: colors.semantic.infoLight,
    background: colors.neutral[50],
    backgroundSecondary: colors.neutral[100],
    surface: '#FFFFFF',
    surfaceSecondary: colors.neutral[100],
    surfaceTertiary: colors.neutral[200],
    text: colors.neutral[900],
    textSecondary: colors.neutral[600],
    textTertiary: colors.neutral[400],
    textInverse: '#FFFFFF',
    border: colors.neutral[200],
    borderLight: colors.neutral[100],
    borderDark: colors.neutral[300],
    card: '#FFFFFF',
    cardSecondary: colors.neutral[50],
    cardShadow: 'rgba(0, 0, 0, 0.08)',
    overlay: 'rgba(0, 0, 0, 0.4)',
    overlayLight: 'rgba(0, 0, 0, 0.2)',
    tabBar: {
      active: colors.brand.primary,
      inactive: colors.neutral[400],
      background: '#FFFFFF',
      border: colors.neutral[200],
    },
    statusBadge: {
      new: colors.semantic.error,
      newLight: colors.semantic.errorLight,
      learning: colors.semantic.warning,
      learningLight: colors.semantic.warningLight,
      mastered: colors.semantic.success,
      masteredLight: colors.semantic.successLight,
    },
    glass: {
      background: 'rgba(255, 255, 255, 0.7)',
      backgroundDark: 'rgba(255, 255, 255, 0.85)',
      border: 'rgba(255, 255, 255, 0.5)',
    },
  },
  typography: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSize,
    fontWeight: typography.fontWeight,
    lineHeight: typography.lineHeight,
    letterSpacing: typography.letterSpacing,
  },
  spacing: spacing,
  borderRadius: borderRadius,
  shadows: shadows,
  animation: animation,
  zIndex: zIndex,
};

export type Theme = typeof lightTheme;
