import { Theme } from './light';
import { colors, typography, spacing, borderRadius, shadows, animation, zIndex } from './tokens';

export const oceanTheme: Theme = {
  name: 'ocean',
  isDark: true,
  colors: {
    brand: {
      primary: '#14B8A6',
      primaryLight: '#2DD4BF',
      primaryDark: '#0D9488',
      secondary: '#0EA5E9',
      secondaryLight: '#38BDF8',
      accent: '#06B6D4',
      accentLight: '#22D3EE',
    },
    primary: '#14B8A6',
    primaryGradient: [...colors.gradients.ocean.slice(0, 2)] as [string, string],
    primaryGradientFull: [...colors.gradients.ocean] as [string, string, string],
    secondary: '#0EA5E9',
    success: colors.semantic.successLight,
    successLight: '#6EE7B7',
    warning: colors.semantic.warningLight,
    warningLight: '#FCD34D',
    error: colors.semantic.errorLight,
    errorLight: '#FCA5A5',
    info: '#38BDF8',
    infoLight: '#7DD3FC',
    background: '#0C1222',
    backgroundSecondary: '#0F172A',
    surface: '#1E293B',
    surfaceSecondary: '#334155',
    surfaceTertiary: '#475569',
    text: '#F1F5F9',
    textSecondary: '#94A3B8',
    textTertiary: '#64748B',
    textInverse: '#0F172A',
    border: '#334155',
    borderLight: '#1E293B',
    borderDark: '#475569',
    card: 'rgba(30, 41, 59, 0.8)',
    cardSecondary: 'rgba(51, 65, 85, 0.6)',
    cardShadow: 'rgba(0, 0, 0, 0.4)',
    overlay: 'rgba(12, 18, 34, 0.7)',
    overlayLight: 'rgba(12, 18, 34, 0.5)',
    tabBar: {
      active: '#2DD4BF',
      inactive: '#64748B',
      background: 'rgba(15, 23, 42, 0.95)',
      border: '#334155',
    },
    statusBadge: {
      new: colors.semantic.errorLight,
      newLight: '#FCA5A5',
      learning: '#FBBF24',
      learningLight: '#FCD34D',
      mastered: '#34D399',
      masteredLight: '#6EE7B7',
    },
    glass: {
      background: 'rgba(30, 41, 59, 0.6)',
      backgroundDark: 'rgba(30, 41, 59, 0.8)',
      border: 'rgba(255, 255, 255, 0.1)',
    },
  },
  typography: {
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSize,
    fontWeight: typography.fontWeight,
    lineHeight: typography.lineHeight,
    letterSpacing: typography.letterSpacing,
  },
  spacing: spacing,
  borderRadius: borderRadius,
  shadows: {
    ...shadows,
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 2,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 4,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.4,
      shadowRadius: 16,
      elevation: 8,
    },
  },
  animation: animation,
  zIndex: zIndex,
};
