// Batch 6: Medical, Legal, Environmental, Economics, Psychology, Internet, AI dual-meaning
module.exports = {
// === Medical/Health ===
"ailment":"n. 小病；不适",
"allergy":"n. 过敏；过敏症",
"amnesia":"n. 失忆症；健忘",
"anemia":"n. 贫血",
"anesthetic":"n./adj. 麻醉剂；麻醉的",
"antibiotic":"n. 抗生素",
"antibody":"n. 抗体",
"antiseptic":"n./adj. 消毒剂；防腐的",
"artery":"n. 动脉；干道",
"asthma":"n. 哮喘",
"autoimmune":"adj. 自身免疫的",
"biopsy":"n. 活检；组织检查",
"cardiac":"adj. 心脏的",
"carcinogenic":"adj. 致癌的",
"cardiovascular":"adj. 心血管的",
"clinical":"adj. 临床的；冷静客观的",
"cognitive":"adj. 认知的；感知的",
"comorbidity":"n. 共病；合并症",
"congenital":"adj. 先天的；天生的",
"contagious":"adj. 传染性的；有感染力的",
"cortisol":"n. 皮质醇（应激激素）",
"degenerative":"adj. 退行性的；退化的",
"dehydration":"n. 脱水",
"dementia":"n. 痴呆症",
"dermatology":"n. 皮肤科学",
"dialysis":"n. 透析",
"dosage":"n. 剂量",
"dysfunction":"n. 功能障碍；失调",
"endocrine":"adj./n. 内分泌的",
"etiology":"n. 病因学",
"gastrointestinal":"adj. 胃肠道的",
"geriatric":"adj. 老年医学的",
"gynecology":"n. 妇科学",
"hemorrhage":"n./v. 大出血",
"hereditary":"adj. 遗传的；世袭的",
"hormone":"n. 激素；荷尔蒙",
"hospice":"n. 临终关怀机构",
"hygiene":"n. 卫生；保健",
"hypertension":"n. 高血压",
"immunology":"n. 免疫学",
"impairment":"n. 损伤；障碍",
"incubation":"n. 潜伏期；孵化",
"inflammation":"n. 炎症；发炎",
"insomnia":"n. 失眠症",
"insulin":"n. 胰岛素",
"malignant":"adj. 恶性的；有害的",
"metabolism":"n. 新陈代谢",
"metastasis":"n. 转移（癌症扩散）",
"neurological":"adj. 神经学的",
"obesity":"n. 肥胖症",
"oncology":"n. 肿瘤学",
"ophthalmology":"n. 眼科学",
"orthopedic":"adj. 骨科的",
"palliative":"adj. 缓和的；姑息的",
"pathogen":"n. 病原体",
"pathology":"n. 病理学",
"pediatric":"adj. 儿科的",
"pharmaceutical":"adj./n. 制药的；药品",
"pharmacology":"n. 药理学",
"physiotherapy":"n. 物理治疗",
"placebo":"n. 安慰剂",
"pneumonia":"n. 肺炎",
"postoperative":"adj. 术后的",
"prenatal":"adj. 产前的",
"prescription":"n. 处方；药方",
"prognosis":"n. 预后；预测",
"prosthetic":"adj./n. 假肢的；假体",
"psychiatric":"adj. 精神病学的",
"pulmonary":"adj. 肺部的",
"radiology":"n. 放射学",
"remission":"n. 缓解期（病情好转）",
"respiratory":"adj. 呼吸的；呼吸系统的",
"sedative":"n./adj. 镇静剂；镇静的",
"seizure":"n. 癫痫发作；没收",
"sepsis":"n. 败血症",
"serum":"n. 血清",
"serotonin":"n. 血清素（快乐激素）",
"steroid":"n. 类固醇",
"stimulant":"n. 兴奋剂；刺激物",
"surgical":"adj. 外科的；手术的",
"symptom":"n. 症状；征兆",
"therapeutic":"adj. 治疗的；有疗效的",
"therapy":"n. 疗法；治疗",
"toxicology":"n. 毒理学",
"triage":"n. 分诊；优先排序",
"tumor":"n. 肿瘤",
"ultrasound":"n. 超声波；B超",
"vaccination":"n. 接种疫苗",
"vaccine":"n. 疫苗",
"ventilator":"n. 呼吸机；通风设备",
"viral":"adj. 病毒的；（网络）疯传的",
"vitamin":"n. 维生素",
// === Legal ===
"acquittal":"n. 宣判无罪；开释",
"affidavit":"n. 宣誓书；书面证词",
"allegation":"n. 指控；断言",
"appeal":"n./v. 上诉；呼吁",
"arbitration":"n. 仲裁",
"arraign":"v. 传讯；提审",
"bail":"n./v. 保释；保释金",
"bailiff":"n. 法警；执行官",
"bankruptcy":"n. 破产；倒闭",
"contempt":"n. 蔑视；藐视法庭",
"counterfeit":"adj./n. 伪造的；赝品",
"custody":"n. 监护权；拘留",
"defendant":"n. 被告",
"deposition":"n. 证词；宣誓作证",
"embezzlement":"n. 贪污；挪用公款",
"enforcement":"n. 执法；强制执行",
"extortion":"n. 勒索；敲诈",
"extradition":"n. 引渡",
"felony":"n. 重罪",
"fiduciary":"adj./n. 信托的；受托人",
"forfeiture":"n. 没收；丧失",
"fraud":"n. 欺诈；骗子",
"habeas corpus":"n. 人身保护令",
"hearing":"n. 听证会；审理",
"homicide":"n. 杀人；凶杀",
"immunity":"n. 免疫力；豁免权",
"incarceration":"n. 监禁；入狱",
"indemnity":"n. 赔偿；保障",
"indictment":"n. 起诉书；控告",
"infringement":"n. 侵权；违反",
"injunction":"n. 禁令；法院命令",
"insolvent":"adj. 破产的；无力偿债的",
"jurisprudence":"n. 法理学；法律体系",
"larceny":"n. 盗窃罪",
"lawsuit":"n. 诉讼；官司",
"litigate":"v. 提起诉讼",
"magistrate":"n. 地方法官",
"malpractice":"n. 玩忽职守；医疗事故",
"mediation":"n. 调解；斡旋",
"misdemeanor":"n. 轻罪；不端行为",
"notarize":"v. 公证",
"oath":"n. 宣誓；誓言",
"obstruction":"n. 阻碍；妨碍司法",
"pardon":"n./v. 赦免；原谅",
"parole":"n. 假释；言语保证",
"perjury":"n. 伪证罪",
"plaintiff":"n. 原告",
"plea":"n. 抗辩；恳求",
"probation":"n. 缓刑；试用期",
"recidivism":"n. 累犯；再犯",
"retainer":"n. 聘金；家臣",
"settlement":"n. 和解；定居点",
"slander":"n./v. 诽谤；中伤",
"solicitor":"n. 律师；法务",
"subpoena":"n./v. 传票；传唤",
"summons":"n. 传票；召唤",
"testimony":"n. 证词；证据",
"trespass":"v./n. 侵入；非法闯入",
"verdict":"n. 裁决；结论",
"whistleblower":"n. 举报人；吹哨人",
// === Environmental ===
"biodegradable":"adj. 可生物降解的",
"biofuel":"n. 生物燃料",
"biomass":"n. 生物质",
"carbon":"n. 碳",
"conservation":"n. 保护；节约",
"contamination":"n. 污染；沾染",
"coral":"n. 珊瑚",
"deforestation":"n. 砍伐森林",
"desertification":"n. 荒漠化",
"ecological":"adj. 生态的",
"effluent":"n. 废水；流出物",
"endangered":"adj. 濒危的",
"extinction":"n. 灭绝；消亡",
"fauna":"n. 动物群",
"flora":"n. 植物群",
"fossil":"n./adj. 化石；化石的",
"geothermal":"adj. 地热的",
"greenhouse":"n./adj. 温室；温室效应的",
"herbicide":"n. 除草剂",
"hydroelectric":"adj. 水力发电的",
"irrigation":"n. 灌溉",
"landfill":"n. 垃圾填埋场",
"marine":"adj. 海洋的；海事的",
"methane":"n. 甲烷",
"nitrogen":"n. 氮",
"organic":"adj. 有机的；天然的",
"ozone":"n. 臭氧",
"permafrost":"n. 永久冻土",
"pesticide":"n. 杀虫剂",
"photosynthesis":"n. 光合作用",
"pollutant":"n. 污染物",
"precipitation":"n. 降水；沉淀",
"predator":"n. 捕食者；掠夺者",
"preservation":"n. 保存；保护",
"radiation":"n. 辐射；放射",
"recyclable":"adj. 可回收的",
"reforestation":"n. 重新造林",
"renewable":"adj. 可再生的",
"reservoir":"n. 水库；储存库",
"runoff":"n. 径流；流走",
"sediment":"n. 沉积物",
"sequestration":"n. 封存（碳封存）",
"smog":"n. 雾霾",
"solar":"adj. 太阳的；太阳能的",
"species":"n. 物种",
"sustainability":"n. 可持续性",
"topography":"n. 地形；地貌",
"toxin":"n. 毒素",
"turbine":"n. 涡轮机",
"wetland":"n. 湿地",
"wildlife":"n. 野生动物",
// === Economics/Finance ===
"amortize":"v. 分期偿还",
"annuity":"n. 年金；养老金",
"appreciation":"n. 增值；欣赏",
"arbitrage":"n. 套利；套汇",
"bearish":"adj. 看跌的；熊市的",
"bond":"n. 债券；纽带",
"brokerage":"n. 经纪业务；佣金",
"bullish":"adj. 看涨的；牛市的",
"capital":"n. 资本；首都",
"cartel":"n. 卡特尔；垄断联盟",
"creditor":"n. 债权人",
"currency":"n. 货币；流通",
"debenture":"n. 公司债券",
"debt":"n. 债务；欠款",
"default":"n./v. 违约；默认",
"deflation":"n. 通货紧缩",
"depreciation":"n. 折旧；贬值",
"derivative":"n./adj. 衍生品；派生的",
"devaluation":"n. 贬值",
"disinflation":"n. 反通胀；通胀降低",
"diversification":"n. 多元化",
"embargo":"n. 禁运",
"equity":"n. 股权；净值；公平",
"escrow":"n. 第三方托管",
"expenditure":"n. 支出；开销",
"fiscal":"adj. 财政的；税务的",
"foreclosure":"n. 抵押品赎回权丧失",
"GDP":"n. 国内生产总值",
"hedge":"n./v. 对冲；避险",
"hyperinflation":"n. 恶性通货膨胀",
"incentive":"n. 激励；动机",
"insolvency":"n. 破产",
"interest":"n. 利息；兴趣；利益",
"inventory":"n. 库存；清单",
"IPO":"n. 首次公开募股",
"ledger":"n. 账本；分类账",
"liquidation":"n. 清算；变现",
"liquidity":"n. 流动性；变现能力",
"macroeconomic":"adj. 宏观经济的",
"markup":"n. 加价；标记",
"maturity":"n. 到期日；成熟",
"microeconomic":"adj. 微观经济的",
"monetize":"v. 货币化；变现",
"NASDAQ":"n. 纳斯达克（美国股票市场）",
"oligopoly":"n. 寡头垄断",
"overhead":"n./adj. 间接费用；头顶的",
"payroll":"n. 工资单；薪资总额",
"portfolio":"n. 投资组合",
"premium":"n. 溢价；保费；高品质",
"procurement":"n. 采购；获取",
"prospectus":"n. 招股说明书",
"rationing":"n. 配给制；限量供应",
"real estate":"n. 房地产",
"receivable":"n./adj. 应收账款",
"refinance":"v. 再融资；重新贷款",
"remittance":"n. 汇款",
"securities":"n. 证券；有价证券",
"shareholder":"n. 股东",
"solvency":"n. 偿付能力",
"speculation":"n. 投机；推测",
"stagflation":"n. 滞胀（停滞+通胀）",
"stock":"n. 股票；库存",
"subsidy":"n. 补贴；津贴",
"taxation":"n. 税收；征税",
"treasury":"n. 国库；财政部",
"underwrite":"v. 承销；担保",
"valuation":"n. 估值；评估",
"venture capital":"n. 风险投资",
// === Psychology/Sociology ===
"addiction":"n. 上瘾；成瘾",
"adolescent":"n./adj. 青少年；青春期的",
"anxiety":"n. 焦虑；不安",
"attachment":"n. 依恋；附件",
"autism":"n. 自闭症",
"behavioral":"adj. 行为的",
"bipolar":"adj. 双极的；躁郁的",
"burnout":"n. 职业倦怠；精疲力竭",
"catharsis":"n. 宣泄；净化",
"compulsion":"n. 强迫；冲动",
"conditioning":"n. 条件反射；调节",
"conformity":"n. 遵从；一致性",
"consciousness":"n. 意识；知觉",
"coping":"n. 应对；处理",
"defense mechanism":"n. 防御机制",
"depression":"n. 抑郁症；萧条",
"desensitization":"n. 脱敏；麻木化",
"deviance":"n. 偏差行为；越轨",
"dissonance":"n. 不协调；认知失调",
"ego":"n. 自我；自负",
"emotional intelligence":"n. 情商",
"extrovert":"n./adj. 外向的人",
"fixation":"n. 固着；执念",
"gratification":"n. 满足；快感",
"groupthink":"n. 群体思维；从众心理",
"hedonism":"n. 享乐主义",
"hysteria":"n. 歇斯底里；过激反应",
"identity":"n. 身份；认同",
"impulse":"n. 冲动；脉冲",
"indoctrination":"n. 灌输思想",
"inhibition":"n. 抑制；拘束",
"insecurity":"n. 不安全感",
"instinct":"n. 本能；直觉",
"introvert":"n./adj. 内向的人",
"isolation":"n. 隔离；孤独",
"loneliness":"n. 孤独；寂寞",
"mania":"n. 狂热；躁狂",
"meditation":"n. 冥想；沉思",
"melancholy":"n./adj. 忧郁；忧伤的",
"mindfulness":"n. 正念；觉知",
"motivation":"n. 动机；积极性",
"narcissism":"n. 自恋；自我陶醉",
"neurosis":"n. 神经症",
"nostalgia":"n. 怀旧；乡愁",
"obsession":"n. 痴迷；执念",
"paranoia":"n. 偏执；妄想症",
"peer pressure":"n. 同伴压力",
"perception":"n. 感知；看法",
"phobia":"n. 恐惧症",
"prejudice":"n./v. 偏见；歧视",
"projection":"n. 投射；预测",
"psychosomatic":"adj. 心身的（心理影响身体）",
"rationalization":"n. 合理化（心理防御）",
"regression":"n. 退行；回归",
"repression":"n. 压抑；压制",
"schema":"n. 图式；认知框架",
"self-esteem":"n. 自尊心",
"socialization":"n. 社会化；社交",
"stigma":"n. 耻辱；污名",
"subconscious":"n./adj. 潜意识；下意识的",
"sublimation":"n. 升华（心理）",
"tolerance":"n. 容忍；耐受",
"trait":"n. 特征；特质",
"withdrawal":"n. 退缩；戒断反应",
// === Internet/Social Media ===
"algorithm":"n. 算法",
"astroturfing":"n. 伪草根运动（假装群众呼声）",
"blockchain":"n. 区块链",
"bot":"n. 机器人程序",
"broadband":"n. 宽带",
"cache":"n./v. 缓存",
"catfish":"n./v. 网络冒充者；假身份欺骗",
"clickbait":"n. 标题党；诱点击内容",
"cloud":"n. 云计算；云端",
"cookie":"n. 浏览器缓存数据",
"crowdfunding":"n. 众筹",
"crowdsourcing":"n. 众包",
"cyberbullying":"n. 网络霸凌",
"dashboard":"n. 仪表盘；控制面板",
"database":"n. 数据库",
"decentralized":"adj. 去中心化的",
"defamation":"n. 诽谤；中伤",
"disinformation":"n. 虚假信息（故意散布）",
"doomscrolling":"n. 末日刷屏（沉迷坏消息）",
"doxxing":"n. 人肉搜索；公开隐私信息",
"drone":"n. 无人机",
"e-commerce":"n. 电子商务",
"encryption":"n. 加密",
"engagement":"n. 互动率；参与度",
"firewall":"n. 防火墙",
"firmware":"n. 固件",
"gaslighting":"n. 精神控制；煤气灯效应",
"geofencing":"n. 地理围栏",
"gig economy":"n. 零工经济",
"hashtag":"n. 话题标签",
"hosting":"n. 托管；主机服务",
"hyperlink":"n. 超链接",
"identity theft":"n. 身份盗窃",
"influencer":"n. 网红；意见领袖",
"IoT":"n. 物联网",
"livestream":"n./v. 直播",
"malware":"n. 恶意软件",
"meme":"n. 模因；网络迷因",
"metadata":"n. 元数据",
"misinformation":"n. 错误信息（非故意）",
"newsletter":"n. 通讯；简报",
"opt-in":"v./n. 选择加入",
"paywall":"n. 付费墙",
"peer-to-peer":"adj. 点对点的",
"phishing":"n. 网络钓鱼",
"pixel":"n. 像素",
"platform":"n. 平台",
"podcast":"n. 播客",
"privacy":"n. 隐私",
"ransomware":"n. 勒索软件",
"router":"n. 路由器",
"scalability":"n. 可扩展性",
"screenshot":"n. 截屏",
"server":"n. 服务器",
"shadowban":"n./v. 影子封禁（暗中限流）",
"spam":"n./v. 垃圾信息",
"spyware":"n. 间谍软件",
"streaming":"n. 流媒体",
"subscriber":"n. 订阅者",
"thread":"n. 帖子串；线程",
"thumbnail":"n. 缩略图",
"traction":"n. 吸引力；进展",
"trending":"adj. 热门的；趋势的",
"troll":"n./v. 网络喷子；恶意挑衅",
"tutorial":"n. 教程",
"two-factor authentication":"n. 双重验证",
"upload":"v./n. 上传",
"URL":"n. 网址",
"username":"n. 用户名",
"verification":"n. 验证；核实",
"VPN":"n. 虚拟专用网络",
"webinar":"n. 网络研讨会",
"widget":"n. 小部件；小工具",
"wireframe":"n. 线框图",
// === AI dual-meaning words (original + AI meaning) ===
"perplexity":"n. 困惑；迷惑｜AI: Perplexity AI搜索引擎；也指语言模型困惑度指标",
"token":"n. 令牌；代币｜AI: 语言模型处理文本的最小单位",
"hallucination":"n. 幻觉；幻想｜AI: 模型自信地生成虚假信息的现象",
"transformer":"n. 变压器；变形者｜AI: 基于注意力机制的深度学习架构",
"agent":"n. 代理人；经纪人｜AI: 能自主决策执行任务的智能体",
"alignment":"n. 对齐；校准｜AI: 使AI行为符合人类价值观",
"attention":"n. 注意力；关注｜AI: Transformer核心的注意力机制",
"epoch":"n. 时代；纪元｜AI: 模型训练完整遍历一次数据",
"prompt":"n./v. 提示；促使｜AI: 给AI模型的输入指令",
"inference":"n. 推理；推断｜AI: 用训练好的模型做预测",
"embedding":"n. 嵌入；镶嵌｜AI: 将文本转为语义向量表示",
"pipeline":"n. 管道；输送线｜AI/技术: 数据处理的多步骤流水线",
"copilot":"n. 副驾驶｜AI: AI编程助手（如GitHub Copilot）",
"cursor":"n. 光标；游标｜AI: Cursor，一款热门AI编程IDE",
"bias":"n. 偏见；偏差｜AI: 模型因训练数据产生的系统性偏差",
"weights":"n. 重量；砝码｜AI: 神经网络的可学习参数",
"dropout":"n. 退学者；辍学｜AI: 随机关闭神经元防过拟合的技术",
"loss":"n. 损失；亏损｜AI: 衡量模型预测误差的损失函数",
"training":"n. 训练；培训｜AI: 用数据调整模型参数的过程",
"fine-tuning":"n. 微调；精调｜AI: 在预训练模型上针对特定任务训练",
"diffusion":"n. 扩散；传播｜AI: 通过去噪过程生成图像的模型",
"reinforcement":"n. 加强；强化｜AI: 通过奖惩信号训练AI的强化学习",
"benchmark":"n. 基准；标杆｜AI: 用标准数据集评估模型性能",
"foundation":"n. 基础；基金会｜AI: 大规模预训练的基础模型",
"frontier":"n. 边界；前沿｜AI: 当前最强的前沿AI模型",
"grounding":"n. 基础；接地｜AI: 让AI输出基于可靠信息源",
"guardrails":"n. 护栏｜AI: 限制AI产生有害输出的安全机制",
"scaffold":"n./v. 脚手架｜AI/技术: 搭建基础代码框架",
"staggering":"adj. 令人震惊的；惊人的",
"algorithmic":"adj. 算法的；基于算法的",
"geopolitical":"adj. 地缘政治的",
"monetary":"adj. 货币的；金融的",
"authoritarian":"adj. 独裁的；专制的",
"populism":"n. 民粹主义",
"oligarch":"n. 寡头；大亨",
"insurrection":"n. 叛乱；暴动",
"annexation":"n. 吞并；兼并",
"filibuster":"n. 冗长演说阻挠议事",
"geopolitics":"n. 地缘政治学",
"stakeholder":"n. 利益相关者"
};
